- name: Install and configure Active Directory on Windows Server
  hosts: windows_vm
  gather_facts: false
  collections:
    - microsoft.ad
  vars:
    dominio_dns: adservice.local
    safe_mode_password: "ElTigre2025+"
  tasks:

    - name: Install the AD-Domain-Services role
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present
      register: ad_feature

    - name: Reboot if required after installing AD DS
      win_reboot:
      when: ad_feature.reboot_required

    - name: Wait for WinRM to become available after reboot
      wait_for_connection:
        port: 5986
        host: "{{ ansible_host }}"
        timeout: 600
      when: ad_feature.reboot_required

    - name: Promote server to domain controller
      microsoft.ad.domain:
        dns_domain_name: "{{ dominio_dns }}"
        safe_mode_password: "{{ safe_mode_password }}"
      register: domain_promotion

    - name: Reboot after domain promotion
      win_reboot:
      when: domain_promotion.changed

    - name: Wait for WinRM to become available after reboot
      wait_for_connection:
        port: 5986
        host: "{{ ansible_host }}"
        timeout: 600
      when: domain_promotion.changed
