all:
  hosts:
    windows_vm:
      ansible_host: ${ad_ip}
      ansible_user: ${ansible_user}
      ansible_password: "${ansible_password}"
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
