all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    web_primary:
      hosts:
        vm-nginx-0:
          ansible_host: "{{ lb_ip }}"
          ansible_port: 5001

    web_secondary:
      hosts:
        vm-nginx-1:
          ansible_host: "{{ lb_ip }}"
          ansible_port: 5002

    web_all:
      hosts:
        vm-nginx-0:
        vm-nginx-1:
