all:
  hosts:
    windows_vm:
      ansible_host: <IP>
      ansible_user: <user>
      ansible_password: "<password>"
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
