name: Deploy WebService Infrastructure with Terraform, Ansible, and Cloudflare

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN }}
      CLOUDFLARE_RECORD_NAME: ${{ secrets.CLOUDFLARE_RECORD_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Initialize Terraform
        working-directory: WebService/terraform
        run: terraform init

      - name: Apply Terraform configuration
        working-directory: WebService/terraform
        run: terraform apply -auto-approve

      - name: Get Load Balancer public IP
        id: get_ip
        run: |
          ip=$(az network public-ip show \
            --resource-group rg-nginx-setup \
            --name lb-public-ip \
            --query "ipAddress" -o tsv)
          echo "lb_ip=$ip" >> $GITHUB_OUTPUT

      - name: Create A record in Cloudflare
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records" \
          -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "type":"A",
            "name":"'"$CLOUDFLARE_RECORD_NAME"'",
            "content":"${{ steps.get_ip.outputs.lb_ip }}",
            "ttl":120,
            "proxied":false
          }'

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Configure NGINX with Ansible
        run: |
          ansible-playbook WebService/ansible/playbooks/setup_nginx.yml \
            -i WebService/ansible/inventory/hosts.yml \
            --extra-vars "lb_ip=${{ steps.get_ip.outputs.lb_ip }}"

      - name: Deallocate VM1
        run: az vm deallocate --name vm-nginx-1 --resource-group rg-nginx-setup

      - name: Set up SSL on VM0
        run: |
          ansible-playbook WebService/ansible/playbooks/setup_ssl.yml \
            -i WebService/ansible/inventory/hosts.yml \
            --limit vm-nginx-0

      - name: Deallocate VM0
        run: az vm deallocate --name vm-nginx-0 --resource-group rg-nginx-setup

      - name: Start VM1
        run: az vm start --name vm-nginx-1 --resource-group rg-nginx-setup

      - name: Set up SSL on VM1
        run: |
          ansible-playbook WebService/ansible/playbooks/setup_ssl.yml \
            -i WebService/ansible/inventory/hosts.yml \
            --limit vm-nginx-1

      - name: Start VM0
        run: az vm start --name vm-nginx-0 --resource-group rg-nginx-setup
