---
- name: Setup NGINX and deploy web app
  hosts: web_all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - php
          - php-ldap
          - php-fpm 
        state: present
        update_cache: yes

    - name: Ensure PHP-FPM is started and enabled
      service:
        name: php8.1-fpm
        state: started
        enabled: yes
        
    - name: Create PHP config for NGINX
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
    
              root /var/www/html;
              index index.php index.html index.htm;
    
              server_name _;
    
              location / {
                  try_files $uri $uri/ =404;
              }
    
              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php8.1-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }
    
              location ~ /\.ht {
                  deny all;
              }
          }
          
    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded

    - name: Ensure NGINX is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Clean up all contents in /var/www/html
      ansible.builtin.shell: rm -rf /var/www/html/{*,.*} || true
      args:
        executable: /bin/bash


    - name: Clone GitHub repo
      git:
        repo: 'https://github.com/LUI5DA/webService-php.git'
        dest: /var/www/html/
        version: main

    - name: Set proper permissions
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
