---
- name: Instalar Certbot y generar certificado en web_primary
  hosts: web_all
  become: yes
  vars:
    domain_name: proyectoredes.site  # <-- reemplaza con tu dominio real
    email: gamezdavid208@gmail.com  # <-- email para notificaciones de Let's Encrypt

  tasks:
    - name: Instalar Certbot y plugin para NGINX
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Obtener certificado SSL de Let's Encrypt
      command: >
        certbot --nginx -n
        --agree-tos
        --redirect
        --hsts
        --email {{ email }}
        -d {{ domain_name }}

    - name: Verificar que el certificado se generó
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: cert_status

    - name: Mostrar resultado
      debug:
        msg: "✅ Certificado generado correctamente"
      when: cert_status.stat.exists

    - name: Recargar NGINX para aplicar cambios de certificado
      service:
        name: nginx
        state: reloaded

